name: Build Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file openjdk/Dockerfile --tag my-image-name:$(date +%s)
